<template>
  <div class="p-2 app-container"><el-card shadow="hover"><template #header><div class="flex items-center justify-between"><div><h3 class="m-0 text-base font-semibold">书评管理</h3><p class="m-0 mt-1 text-sm text-[var(--el-text-color-secondary)]">隐藏后的内容不会在移动端展示。</p></div><div><el-button :disabled="!selectedRows.length" @click="batchStatus('HIDDEN')">批量隐藏</el-button><el-button type="primary" :disabled="!selectedRows.length" @click="batchStatus('VISIBLE')">批量恢复</el-button></div></div></template>
    <el-form :inline="true" :model="query" @submit.prevent><el-form-item label="关键词"><el-input v-model="query.keyword" clearable @keyup.enter="loadList" /></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable style="width: 130px"><el-option label="展示中" value="VISIBLE" /><el-option label="已隐藏" value="HIDDEN" /><el-option label="已删除" value="DELETED" /></el-select></el-form-item><el-button type="primary" icon="Search" @click="loadList">查询</el-button></el-form>
    <el-table v-loading="loading" :data="rows" border @selection-change="selectedRows = $event"><el-table-column type="selection" width="48" /><el-table-column label="作品" prop="workTitle" min-width="160" /><el-table-column label="读者" prop="nickName" width="130" /><el-table-column label="评分" prop="score" width="80" /><el-table-column label="书评内容" prop="commentContent" min-width="280" show-overflow-tooltip /><el-table-column label="点赞" prop="likeCount" width="80" /><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 'VISIBLE' ? 'success' : row.status === 'HIDDEN' ? 'warning' : 'info'">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="提交时间" prop="createTime" min-width="180" /><el-table-column label="操作" fixed="right" width="140"><template #default="{ row }"><el-button v-if="row.status !== 'VISIBLE'" link type="success" @click="changeStatus(row, 'VISIBLE')">恢复展示</el-button><el-button v-else link type="warning" @click="changeStatus(row, 'HIDDEN')">隐藏</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" v-model:page="query.pageNum" v-model:limit="query.pageSize" :total="total" @pagination="loadList" />
  </el-card></div>
</template>
<script setup lang="ts">
import { batchUpdateReaderH5CommentStatus, listReaderH5Comments, updateReaderH5CommentStatus } from '@/api/reader/admin';
import type { ReaderReadingCommentAdminQuery, ReaderReadingCommentAdminVO } from '@/api/reader/admin/types';
defineOptions({ name: 'ReaderAdminH5CommentPage' });
const loading = ref(false); const rows = ref<ReaderReadingCommentAdminVO[]>([]); const selectedRows = ref<ReaderReadingCommentAdminVO[]>([]); const total = ref(0); const query = reactive<ReaderReadingCommentAdminQuery>({ pageNum: 1, pageSize: 10, keyword: undefined, status: undefined });
const statusLabel = (status: string) => status === 'VISIBLE' ? '展示中' : status === 'HIDDEN' ? '已隐藏' : '已删除';
const loadList = async () => { loading.value = true; try { const { data } = await listReaderH5Comments(query); rows.value = data?.rows ?? []; total.value = Number(data?.total ?? 0); } finally { loading.value = false; } };
const changeStatus = async (row: ReaderReadingCommentAdminVO, status: string) => { await updateReaderH5CommentStatus(row.id, status); ElMessage.success('书评状态已更新'); await loadList(); };
const batchStatus = async (status: string) => { if (!selectedRows.value.length) return ElMessage.warning('请先选择书评'); await ElMessageBox.confirm(`确认批量${status === 'VISIBLE' ? '恢复展示' : '隐藏'} ${selectedRows.value.length} 条书评吗？`, '批量操作确认', { type: 'warning' }); const { data } = await batchUpdateReaderH5CommentStatus(selectedRows.value.map(row => row.id), status); ElMessage.success(`批量操作完成，成功 ${data?.successCount ?? 0} 条，失败 ${data?.failureCount ?? 0} 条`); selectedRows.value = []; await loadList(); };
onMounted(loadList);
</script>
